- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP Agent on CentOS 
      ansible.builtin.yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"
      
    - name: Install NTP Agent on Ubuntu 
      ansible.builtin.apt:
        name: ntp
        state: present    
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Service on CentOS
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
    
    - name: Start Service on Ubuntu
      ansible.builtin.service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
      
            
      
   
