- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install maria-db-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Start mariab-db-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
         
