# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: Print current user
      run: |
        whoami
        pwd
